name: CI - Testes Unitários

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Configurar JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'maven'

      - name: Instalar dependências
        run: mvn clean install -DskipTests
        working-directory: aplicacaonutricao

      - name: Executar testes unitários
        run: mvn test
        working-directory: aplicacaonutricao

      
